# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/system_ZedboardOLED_0_0.xci
# IP: The module: 'system_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/src/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]

# XDC: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc

# IP: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/system_ZedboardOLED_0_0.xci
# IP: The module: 'system_ZedboardOLED_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/src/charLib/charLib.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib}]

# XDC: c:/Users/Jorge/Desktop/Uni/MASTER/Digital/lab/_Zynq_C/Zynq_C/Zynq_C.srcs/sources_1/bd/system/ip/system_ZedboardOLED_0_0/src/charLib/charLib_ooc.xdc
