webtalk_init -webtalk_dir C:\\Users\\Jorge\\Desktop\\Uni\\MASTER\\Digital\\lab\\_Zynq_C\\Zynq_C\\Zynq_C.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-14 19:01:45" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l1lljkme80ob15q4qqb2t5rvj9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.1_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1526313959408" -context "sdk\\\\bsp/1526313959408"
webtalk_add_data -client sdk -key hwid -value "1526143569406" -context "sdk\\\\bsp/1526313959408"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1526313959408"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1526313959408"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1526313959408"
webtalk_add_data -client sdk -key uid -value "1526313970519" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key hwid -value "1526143569406" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key bspid -value "1526313959408" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1526313970519"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1526317305369"
webtalk_transmit -clientid 536879861 -regid "" -xml C:\\Users\\Jorge\\Desktop\\Uni\\MASTER\\Digital\\lab\\_Zynq_C\\Zynq_C\\Zynq_C.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Jorge\\Desktop\\Uni\\MASTER\\Digital\\lab\\_Zynq_C\\Zynq_C\\Zynq_C.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Jorge\\Desktop\\Uni\\MASTER\\Digital\\lab\\_Zynq_C\\Zynq_C\\Zynq_C.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
